package com.Entities;
// Generated Dec 8, 2017 3:43:31 AM by Hibernate Tools 5.2.6.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Banners generated by hbm2java
 */
@Entity
@Table(name = "Banners", catalog = "SHOP")
public class Banners implements java.io.Serializable {

	private int bannerId;
	private String bannerImgUrl;
	private String bannerName;
	private Serializable saleOff;
	private Serializable bannerContent;
	private Serializable bannerPrice;

	public Banners() {
	}

	public Banners(int bannerId, String bannerImgUrl) {
		this.bannerId = bannerId;
		this.bannerImgUrl = bannerImgUrl;
	}

	public Banners(int bannerId, String bannerImgUrl, String bannerName, Serializable saleOff,
			Serializable bannerContent, Serializable bannerPrice) {
		this.bannerId = bannerId;
		this.bannerImgUrl = bannerImgUrl;
		this.bannerName = bannerName;
		this.saleOff = saleOff;
		this.bannerContent = bannerContent;
		this.bannerPrice = bannerPrice;
	}

	@Id

	@Column(name = "Banner_id", unique = true, nullable = false)
	public int getBannerId() {
		return this.bannerId;
	}

	public void setBannerId(int bannerId) {
		this.bannerId = bannerId;
	}

	@Column(name = "Banner_img_url", nullable = false, length = 150)
	public String getBannerImgUrl() {
		return this.bannerImgUrl;
	}

	public void setBannerImgUrl(String bannerImgUrl) {
		this.bannerImgUrl = bannerImgUrl;
	}

	@Column(name = "Banner_name", length = 50)
	public String getBannerName() {
		return this.bannerName;
	}

	public void setBannerName(String bannerName) {
		this.bannerName = bannerName;
	}

	@Column(name = "Sale_off")
	public Serializable getSaleOff() {
		return this.saleOff;
	}

	public void setSaleOff(Serializable saleOff) {
		this.saleOff = saleOff;
	}

	@Column(name = "Banner_content")
	public Serializable getBannerContent() {
		return this.bannerContent;
	}

	public void setBannerContent(Serializable bannerContent) {
		this.bannerContent = bannerContent;
	}

	@Column(name = "Banner_price")
	public Serializable getBannerPrice() {
		return this.bannerPrice;
	}

	public void setBannerPrice(Serializable bannerPrice) {
		this.bannerPrice = bannerPrice;
	}

}
