package com.Entities;
// Generated Dec 8, 2017 11:00:44 AM by Hibernate Tools 5.2.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Banners generated by hbm2java
 */
@Entity
@Table(name = "Banners", catalog = "SHOP")
public class Banners implements java.io.Serializable {

	private int bannerId;
	private String bannerImgUrl;
	private String bannerName;
	private String sale_off;
	private String banner_content;
	private String banner_price;

	public Banners() {
	}

	public Banners(int bannerId, String bannerImgUrl) {
		this.bannerId = bannerId;
		this.bannerImgUrl = bannerImgUrl;
	}

	public Banners(int bannerId, String bannerImgUrl, String bannerName, String sale_off, String banner_content,
			String banner_price) {
		this.bannerId = bannerId;
		this.bannerImgUrl = bannerImgUrl;
		this.bannerName = bannerName;
		this.sale_off = sale_off;
		this.banner_content = banner_content;
		this.banner_price = banner_price;
	}

	@Id

	@Column(name = "Banner_id", unique = true, nullable = false)
	public int getBannerId() {
		return this.bannerId;
	}

	public void setBannerId(int bannerId) {
		this.bannerId = bannerId;
	}

	@Column(name = "Banner_img_url", length = 150)
	public String getBannerImgUrl() {
		return this.bannerImgUrl;
	}

	public void setBannerImgUrl(String bannerImgUrl) {
		this.bannerImgUrl = bannerImgUrl;
	}

	@Column(name = "Banner_name", length = 50)
	public String getBannerName() {
		return this.bannerName;
	}

	public void setBannerName(String bannerName) {
		this.bannerName = bannerName;
	}

	@Column(name = "Banner_content", length = 500)
	public String getbanner_content() {
		return this.banner_content;
	}
	
	public void setBanner_content(String banner_content) {
		this.banner_content = banner_content;
	}


	@Column(name = "Sale_off", length = 100)
	public String getSale_off() {
		return sale_off;
	}

	public void setSale_off(String sale_off) {
		this.sale_off = sale_off;
	}

	@Column(name = "Banner_price", length = 50)
	public String getBanner_price() {
		return this.banner_price;
	}

	public void setBanner_price(String banner_price) {
		this.banner_price = banner_price;
	}

}
