package com.Entities;
// Generated Dec 8, 2017 3:43:31 AM by Hibernate Tools 5.2.6.Final

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Carts generated by hbm2java
 */
@Entity
@Table(name = "Carts", catalog = "SHOP")
public class Carts implements java.io.Serializable {

	private int cartId;
	private Customers customers;
	private Employees employees;
	private PaymentMethod paymentMethod;
	private Date cartDate;
	private BigDecimal cartTotal;
	private Serializable shipAddress;
	private Date shipDate;
	private int cartStatus;
	private int shipStatus;
	private int payStatus;
	private Set<CartDetails> cartDetailses = new HashSet<CartDetails>(0);

	public Carts() {
	}

	public Carts(int cartId, Date cartDate, BigDecimal cartTotal, Serializable shipAddress, Date shipDate,
			int cartStatus, int shipStatus, int payStatus) {
		this.cartId = cartId;
		this.cartDate = cartDate;
		this.cartTotal = cartTotal;
		this.shipAddress = shipAddress;
		this.shipDate = shipDate;
		this.cartStatus = cartStatus;
		this.shipStatus = shipStatus;
		this.payStatus = payStatus;
	}

	public Carts(int cartId, Customers customers, Employees employees, PaymentMethod paymentMethod, Date cartDate,
			BigDecimal cartTotal, Serializable shipAddress, Date shipDate, int cartStatus, int shipStatus,
			int payStatus, Set<CartDetails> cartDetailses) {
		this.cartId = cartId;
		this.customers = customers;
		this.employees = employees;
		this.paymentMethod = paymentMethod;
		this.cartDate = cartDate;
		this.cartTotal = cartTotal;
		this.shipAddress = shipAddress;
		this.shipDate = shipDate;
		this.cartStatus = cartStatus;
		this.shipStatus = shipStatus;
		this.payStatus = payStatus;
		this.cartDetailses = cartDetailses;
	}

	@Id

	@Column(name = "Cart_Id", unique = true, nullable = false)
	public int getCartId() {
		return this.cartId;
	}

	public void setCartId(int cartId) {
		this.cartId = cartId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Customer_id")
	public Customers getCustomers() {
		return this.customers;
	}

	public void setCustomers(Customers customers) {
		this.customers = customers;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Emp_id")
	public Employees getEmployees() {
		return this.employees;
	}

	public void setEmployees(Employees employees) {
		this.employees = employees;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Payment_id")
	public PaymentMethod getPaymentMethod() {
		return this.paymentMethod;
	}

	public void setPaymentMethod(PaymentMethod paymentMethod) {
		this.paymentMethod = paymentMethod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Cart_date", nullable = false, length = 23)
	public Date getCartDate() {
		return this.cartDate;
	}

	public void setCartDate(Date cartDate) {
		this.cartDate = cartDate;
	}

	@Column(name = "Cart_total", nullable = false, scale = 4)
	public BigDecimal getCartTotal() {
		return this.cartTotal;
	}

	public void setCartTotal(BigDecimal cartTotal) {
		this.cartTotal = cartTotal;
	}

	@Column(name = "Ship_address", nullable = false)
	public Serializable getShipAddress() {
		return this.shipAddress;
	}

	public void setShipAddress(Serializable shipAddress) {
		this.shipAddress = shipAddress;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Ship_date", nullable = false, length = 23)
	public Date getShipDate() {
		return this.shipDate;
	}

	public void setShipDate(Date shipDate) {
		this.shipDate = shipDate;
	}

	@Column(name = "Cart_status", nullable = false)
	public int getCartStatus() {
		return this.cartStatus;
	}

	public void setCartStatus(int cartStatus) {
		this.cartStatus = cartStatus;
	}

	@Column(name = "Ship_status", nullable = false)
	public int getShipStatus() {
		return this.shipStatus;
	}

	public void setShipStatus(int shipStatus) {
		this.shipStatus = shipStatus;
	}

	@Column(name = "Pay_status", nullable = false)
	public int getPayStatus() {
		return this.payStatus;
	}

	public void setPayStatus(int payStatus) {
		this.payStatus = payStatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "carts")
	public Set<CartDetails> getCartDetailses() {
		return this.cartDetailses;
	}

	public void setCartDetailses(Set<CartDetails> cartDetailses) {
		this.cartDetailses = cartDetailses;
	}

}
