package com.Entities;
// Generated Dec 8, 2017 3:43:31 AM by Hibernate Tools 5.2.6.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CartDetails generated by hbm2java
 */
@Entity
@Table(name = "Cart_Details", catalog = "SHOP")
public class CartDetails implements java.io.Serializable {

	private int cartDetailsId;
	private Carts carts;
	private Products products;
	private Integer quantity;
	private BigDecimal price;

	public CartDetails() {
	}

	public CartDetails(int cartDetailsId, Products products) {
		this.cartDetailsId = cartDetailsId;
		this.products = products;
	}

	public CartDetails(int cartDetailsId, Carts carts, Products products, Integer quantity, BigDecimal price) {
		this.cartDetailsId = cartDetailsId;
		this.carts = carts;
		this.products = products;
		this.quantity = quantity;
		this.price = price;
	}

	@Id

	@Column(name = "Cart_details_id", unique = true, nullable = false)
	public int getCartDetailsId() {
		return this.cartDetailsId;
	}

	public void setCartDetailsId(int cartDetailsId) {
		this.cartDetailsId = cartDetailsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Cart_id")
	public Carts getCarts() {
		return this.carts;
	}

	public void setCarts(Carts carts) {
		this.carts = carts;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Product_id", nullable = false)
	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	@Column(name = "Quantity")
	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	@Column(name = "Price", scale = 4)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

}
