package com.Entities;
// Generated Dec 8, 2017 11:00:44 AM by Hibernate Tools 5.2.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SeoKeywords generated by hbm2java
 */
@Entity
@Table(name = "SEO_keywords", catalog = "SHOP")
public class SeoKeywords implements java.io.Serializable {

	private int keywordId;
	private String keyword;

	public SeoKeywords() {
	}

	public SeoKeywords(int keywordId, String keyword) {
		this.keywordId = keywordId;
		this.keyword = keyword;
	}

	@Id

	@Column(name = "Keyword_id", unique = true, nullable = false)
	public int getKeywordId() {
		return this.keywordId;
	}

	public void setKeywordId(int keywordId) {
		this.keywordId = keywordId;
	}

	@Column(name = "Keyword", nullable = false)
	public String getKeyword() {
		return this.keyword;
	}

	public void setKeyword(String keyword) {
		this.keyword = keyword;
	}

}
