package com.Entities;
// Generated Nov 30, 2017 5:46:37 AM by Hibernate Tools 5.2.6.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SeoKeywords generated by hbm2java
 */
@Entity
@Table(name = "SEO_keywords", catalog = "SHOP")
public class SeoKeywords implements java.io.Serializable {

	private int keywordId;
	private Serializable keyword;

	public SeoKeywords() {
	}

	public SeoKeywords(int keywordId, Serializable keyword) {
		this.keywordId = keywordId;
		this.keyword = keyword;
	}

	@Id

	@Column(name = "Keyword_id", unique = true, nullable = false)
	public int getKeywordId() {
		return this.keywordId;
	}

	public void setKeywordId(int keywordId) {
		this.keywordId = keywordId;
	}

	@Column(name = "Keyword", nullable = false)
	public Serializable getKeyword() {
		return this.keyword;
	}

	public void setKeyword(Serializable keyword) {
		this.keyword = keyword;
	}

}
