package com.Entities;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categories generated by hbm2java
 */
@Entity
@Table(name = "Categories", catalog = "Markito")
public class Categories{

	private String categoryId;
	private Catalogs catalogs;
	private String categoryName;
	private Boolean caStatus;
	private Set<Products> productses = new HashSet<Products>(0);

	public Categories() {
	}

	public Categories(String categoryId, Catalogs catalogs, String categoryName) {
		this.categoryId = categoryId;
		this.catalogs = catalogs;
		this.categoryName = categoryName;
	}

	public Categories(String categoryId, Catalogs catalogs, String categoryName, Boolean caStatus,
			Set<Products> productses) {
		this.categoryId = categoryId;
		this.catalogs = catalogs;
		this.categoryName = categoryName;
		this.caStatus = caStatus;
		this.productses = productses;
	}

	@Id

	@Column(name = "Category_id", unique = true, nullable = false, length = 10)
	public String getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(String categoryId) {
		this.categoryId = categoryId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Catalog_id", nullable = false)
	public Catalogs getCatalogs() {
		return this.catalogs;
	}

	public void setCatalogs(Catalogs catalogs) {
		this.catalogs = catalogs;
	}

	@Column(name = "Category_name", nullable = false)
	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	@Column(name = "Ca_status")
	public Boolean getCaStatus() {
		return this.caStatus;
	}

	public void setCaStatus(Boolean caStatus) {
		this.caStatus = caStatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categories")
	public Set<Products> getProductses() {
		return this.productses;
	}

	public void setProductses(Set<Products> productses) {
		this.productses = productses;
	}

}
