package com.Entities;
// Generated Nov 17, 2017 1:01:03 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Banners generated by hbm2java
 */
@Entity
@Table(name = "Banners", catalog = "SHOP")
public class Banners implements java.io.Serializable {

	private int bannerId;
	private String bannerImgUrl;
	private String bannerName;

	public Banners() {
	}

	public Banners(int bannerId, String bannerImgUrl) {
		this.bannerId = bannerId;
		this.bannerImgUrl = bannerImgUrl;
	}

	public Banners(int bannerId, String bannerImgUrl, String bannerName) {
		this.bannerId = bannerId;
		this.bannerImgUrl = bannerImgUrl;
		this.bannerName = bannerName;
	}

	@Id

	@Column(name = "Banner_id", unique = true, nullable = false)
	public int getBannerId() {
		return this.bannerId;
	}

	public void setBannerId(int bannerId) {
		this.bannerId = bannerId;
	}

	@Column(name = "Banner_img_url", nullable = false, length = 150)
	public String getBannerImgUrl() {
		return this.bannerImgUrl;
	}

	public void setBannerImgUrl(String bannerImgUrl) {
		this.bannerImgUrl = bannerImgUrl;
	}

	@Column(name = "Banner_name", length = 50)
	public String getBannerName() {
		return this.bannerName;
	}

	public void setBannerName(String bannerName) {
		this.bannerName = bannerName;
	}

}
