package com.Entities;
// Generated Nov 7, 2017 9:59:36 AM by Hibernate Tools 5.2.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CartDetailsId generated by hbm2java
 */
@Embeddable
public class CartDetailsId implements java.io.Serializable {

	private String cartId;
	private String productId;

	public CartDetailsId() {
	}

	public CartDetailsId(String cartId, String productId) {
		this.cartId = cartId;
		this.productId = productId;
	}

	@Column(name = "CartId", nullable = false, length = 10)
	public String getCartId() {
		return this.cartId;
	}

	public void setCartId(String cartId) {
		this.cartId = cartId;
	}

	@Column(name = "Product_id", nullable = false, length = 10)
	public String getProductId() {
		return this.productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CartDetailsId))
			return false;
		CartDetailsId castOther = (CartDetailsId) other;

		return ((this.getCartId() == castOther.getCartId()) || (this.getCartId() != null
				&& castOther.getCartId() != null && this.getCartId().equals(castOther.getCartId())))
				&& ((this.getProductId() == castOther.getProductId()) || (this.getProductId() != null
						&& castOther.getProductId() != null && this.getProductId().equals(castOther.getProductId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCartId() == null ? 0 : this.getCartId().hashCode());
		result = 37 * result + (getProductId() == null ? 0 : this.getProductId().hashCode());
		return result;
	}

}
