package com.Entities;
// Generated Nov 7, 2017 9:59:36 AM by Hibernate Tools 5.2.5.Final

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Carts generated by hbm2java
 */
@Entity
@Table(name = "Carts", schema = "dbo", catalog = "SHOP")
public class Carts implements java.io.Serializable {

	private String cartId;
	private Accounts accounts;
	private Date createdDate;
	private int cartStatus;
	private Serializable deliveryAddress;
	private Date deliveryTime;
	private int deliveryStatus;
	private BigDecimal cartTotal;
	private Set<CartDetails> cartDetailses = new HashSet<CartDetails>(0);

	public Carts() {
	}

	public Carts(String cartId, Accounts accounts, Date createdDate, int cartStatus, Serializable deliveryAddress,
			Date deliveryTime, int deliveryStatus, BigDecimal cartTotal) {
		this.cartId = cartId;
		this.accounts = accounts;
		this.createdDate = createdDate;
		this.cartStatus = cartStatus;
		this.deliveryAddress = deliveryAddress;
		this.deliveryTime = deliveryTime;
		this.deliveryStatus = deliveryStatus;
		this.cartTotal = cartTotal;
	}

	public Carts(String cartId, Accounts accounts, Date createdDate, int cartStatus, Serializable deliveryAddress,
			Date deliveryTime, int deliveryStatus, BigDecimal cartTotal, Set<CartDetails> cartDetailses) {
		this.cartId = cartId;
		this.accounts = accounts;
		this.createdDate = createdDate;
		this.cartStatus = cartStatus;
		this.deliveryAddress = deliveryAddress;
		this.deliveryTime = deliveryTime;
		this.deliveryStatus = deliveryStatus;
		this.cartTotal = cartTotal;
		this.cartDetailses = cartDetailses;
	}

	@Id

	@Column(name = "CartId", unique = true, nullable = false, length = 10)
	public String getCartId() {
		return this.cartId;
	}

	public void setCartId(String cartId) {
		this.cartId = cartId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Username", nullable = false)
	public Accounts getAccounts() {
		return this.accounts;
	}

	public void setAccounts(Accounts accounts) {
		this.accounts = accounts;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedDate", nullable = false, length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CartStatus", nullable = false)
	public int getCartStatus() {
		return this.cartStatus;
	}

	public void setCartStatus(int cartStatus) {
		this.cartStatus = cartStatus;
	}

	@Column(name = "DeliveryAddress", nullable = false)
	public Serializable getDeliveryAddress() {
		return this.deliveryAddress;
	}

	public void setDeliveryAddress(Serializable deliveryAddress) {
		this.deliveryAddress = deliveryAddress;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DeliveryTime", nullable = false, length = 23)
	public Date getDeliveryTime() {
		return this.deliveryTime;
	}

	public void setDeliveryTime(Date deliveryTime) {
		this.deliveryTime = deliveryTime;
	}

	@Column(name = "DeliveryStatus", nullable = false)
	public int getDeliveryStatus() {
		return this.deliveryStatus;
	}

	public void setDeliveryStatus(int deliveryStatus) {
		this.deliveryStatus = deliveryStatus;
	}

	@Column(name = "CartTotal", nullable = false, scale = 4)
	public BigDecimal getCartTotal() {
		return this.cartTotal;
	}

	public void setCartTotal(BigDecimal cartTotal) {
		this.cartTotal = cartTotal;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "carts")
	public Set<CartDetails> getCartDetailses() {
		return this.cartDetailses;
	}

	public void setCartDetailses(Set<CartDetails> cartDetailses) {
		this.cartDetailses = cartDetailses;
	}

}
