package com.Entities;
// Generated Nov 7, 2017 9:59:36 AM by Hibernate Tools 5.2.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CartDetails generated by hbm2java
 */
@Entity
@Table(name = "Cart_Details", schema = "dbo", catalog = "SHOP")
public class CartDetails implements java.io.Serializable {

	private CartDetailsId id;
	private Carts carts;
	private Products products;
	private int quantity;
	private BigDecimal price;
	private Date pickedDate;

	public CartDetails() {
	}

	public CartDetails(CartDetailsId id, Carts carts, Products products, int quantity, BigDecimal price,
			Date pickedDate) {
		this.id = id;
		this.carts = carts;
		this.products = products;
		this.quantity = quantity;
		this.price = price;
		this.pickedDate = pickedDate;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "cartId", column = @Column(name = "CartId", nullable = false, length = 10)),
			@AttributeOverride(name = "productId", column = @Column(name = "Product_id", nullable = false, length = 10)) })
	public CartDetailsId getId() {
		return this.id;
	}

	public void setId(CartDetailsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CartId", nullable = false, insertable = false, updatable = false)
	public Carts getCarts() {
		return this.carts;
	}

	public void setCarts(Carts carts) {
		this.carts = carts;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Product_id", nullable = false, insertable = false, updatable = false)
	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	@Column(name = "Quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Column(name = "Price", nullable = false, scale = 4)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PickedDate", nullable = false, length = 23)
	public Date getPickedDate() {
		return this.pickedDate;
	}

	public void setPickedDate(Date pickedDate) {
		this.pickedDate = pickedDate;
	}

}
