package com.Entities;
// Generated Nov 17, 2017 1:01:03 PM by Hibernate Tools 5.2.5.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PaymentMethod generated by hbm2java
 */
@Entity
@Table(name = "Payment_method", catalog = "SHOP")
public class PaymentMethod implements java.io.Serializable {

	private int paymentId;
	private Serializable paymentName;
	private Serializable paymentSupplier;
	private Serializable paymentDescription;
	private Set<Carts> cartses = new HashSet<Carts>(0);

	public PaymentMethod() {
	}

	public PaymentMethod(int paymentId, Serializable paymentName, Serializable paymentSupplier) {
		this.paymentId = paymentId;
		this.paymentName = paymentName;
		this.paymentSupplier = paymentSupplier;
	}

	public PaymentMethod(int paymentId, Serializable paymentName, Serializable paymentSupplier,
			Serializable paymentDescription, Set<Carts> cartses) {
		this.paymentId = paymentId;
		this.paymentName = paymentName;
		this.paymentSupplier = paymentSupplier;
		this.paymentDescription = paymentDescription;
		this.cartses = cartses;
	}

	@Id

	@Column(name = "Payment_id", unique = true, nullable = false)
	public int getPaymentId() {
		return this.paymentId;
	}

	public void setPaymentId(int paymentId) {
		this.paymentId = paymentId;
	}

	@Column(name = "Payment_name", nullable = false)
	public Serializable getPaymentName() {
		return this.paymentName;
	}

	public void setPaymentName(Serializable paymentName) {
		this.paymentName = paymentName;
	}

	@Column(name = "Payment_supplier", nullable = false)
	public Serializable getPaymentSupplier() {
		return this.paymentSupplier;
	}

	public void setPaymentSupplier(Serializable paymentSupplier) {
		this.paymentSupplier = paymentSupplier;
	}

	@Column(name = "Payment_description")
	public Serializable getPaymentDescription() {
		return this.paymentDescription;
	}

	public void setPaymentDescription(Serializable paymentDescription) {
		this.paymentDescription = paymentDescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "paymentMethod")
	public Set<Carts> getCartses() {
		return this.cartses;
	}

	public void setCartses(Set<Carts> cartses) {
		this.cartses = cartses;
	}

}
