package com.Entities;
// Generated Nov 17, 2017 1:01:03 PM by Hibernate Tools 5.2.5.Final

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Products generated by hbm2java
 */
@Entity
@Table(name = "Products", catalog = "SHOP")
public class Products implements java.io.Serializable {

	private String productId;
	private Categories categories;
	private Suppliers suppliers;
	private Serializable productName;
	private String pictureId;
	private int quantity;
	private BigDecimal price;
	private Serializable describe;
	private Integer discount;
	private Boolean prStatus;
	private Set<Pictures> pictureses = new HashSet<Pictures>(0);
	private Set<CartDetails> cartDetailses = new HashSet<CartDetails>(0);

	public Products() {
	}

	public Products(String productId, Categories categories, Suppliers suppliers, Serializable productName,
			String pictureId, int quantity) {
		this.productId = productId;
		this.categories = categories;
		this.suppliers = suppliers;
		this.productName = productName;
		this.pictureId = pictureId;
		this.quantity = quantity;
	}

	public Products(String productId, Categories categories, Suppliers suppliers, Serializable productName,
			String pictureId, int quantity, BigDecimal price, Serializable describe, Integer discount, Boolean prStatus,
			Set<Pictures> pictureses, Set<CartDetails> cartDetailses) {
		this.productId = productId;
		this.categories = categories;
		this.suppliers = suppliers;
		this.productName = productName;
		this.pictureId = pictureId;
		this.quantity = quantity;
		this.price = price;
		this.describe = describe;
		this.discount = discount;
		this.prStatus = prStatus;
		this.pictureses = pictureses;
		this.cartDetailses = cartDetailses;
	}

	@Id

	@Column(name = "Product_id", unique = true, nullable = false, length = 10)
	public String getProductId() {
		return this.productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Category_id", nullable = false)
	public Categories getCategories() {
		return this.categories;
	}

	public void setCategories(Categories categories) {
		this.categories = categories;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Supplier_id", nullable = false)
	public Suppliers getSuppliers() {
		return this.suppliers;
	}

	public void setSuppliers(Suppliers suppliers) {
		this.suppliers = suppliers;
	}

	@Column(name = "Product_name", nullable = false)
	public Serializable getProductName() {
		return this.productName;
	}

	public void setProductName(Serializable productName) {
		this.productName = productName;
	}

	@Column(name = "Picture_id", nullable = false, length = 10)
	public String getPictureId() {
		return this.pictureId;
	}

	public void setPictureId(String pictureId) {
		this.pictureId = pictureId;
	}

	@Column(name = "Quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Column(name = "Price", scale = 4)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "Describe")
	public Serializable getDescribe() {
		return this.describe;
	}

	public void setDescribe(Serializable describe) {
		this.describe = describe;
	}

	@Column(name = "Discount")
	public Integer getDiscount() {
		return this.discount;
	}

	public void setDiscount(Integer discount) {
		this.discount = discount;
	}

	@Column(name = "Pr_status")
	public Boolean getPrStatus() {
		return this.prStatus;
	}

	public void setPrStatus(Boolean prStatus) {
		this.prStatus = prStatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "products")
	public Set<Pictures> getPictureses() {
		return this.pictureses;
	}

	public void setPictureses(Set<Pictures> pictureses) {
		this.pictureses = pictureses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "products")
	public Set<CartDetails> getCartDetailses() {
		return this.cartDetailses;
	}

	public void setCartDetailses(Set<CartDetails> cartDetailses) {
		this.cartDetailses = cartDetailses;
	}

}
