package com.Entities;
// Generated Nov 7, 2017 9:59:36 AM by Hibernate Tools 5.2.5.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Suppliers generated by hbm2java
 */
@Entity
@Table(name = "Suppliers", schema = "dbo", catalog = "SHOP")
public class Suppliers implements java.io.Serializable {

	private Integer supplierId;
	private Serializable supplierName;
	private Set<Products> productses = new HashSet<Products>(0);

	public Suppliers() {
	}

	public Suppliers(Serializable supplierName) {
		this.supplierName = supplierName;
	}

	public Suppliers(Serializable supplierName, Set<Products> productses) {
		this.supplierName = supplierName;
		this.productses = productses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Supplier_id", unique = true, nullable = false)
	public Integer getSupplierId() {
		return this.supplierId;
	}

	public void setSupplierId(Integer supplierId) {
		this.supplierId = supplierId;
	}

	@Column(name = "Supplier_name", nullable = false)
	public Serializable getSupplierName() {
		return this.supplierName;
	}

	public void setSupplierName(Serializable supplierName) {
		this.supplierName = supplierName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "suppliers")
	public Set<Products> getProductses() {
		return this.productses;
	}

	public void setProductses(Set<Products> productses) {
		this.productses = productses;
	}

}
