package com.Entities;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Banners generated by hbm2java
 */
@Entity
@Table(name = "Banners", catalog = "Markito")
public class Banners {

	private int bannerId;
	private String bannerImgUrl;
	private String bannerName;
	private String sale_off;
	private String banner_content;

	public Banners() {
	}

	public Banners(int bannerId) {
		this.bannerId = bannerId;
	}

	public Banners(int bannerId, String bannerImgUrl, String bannerName, String sale_off, String banner_content) {
		this.bannerId = bannerId;
		this.bannerImgUrl = bannerImgUrl;
		this.bannerName = bannerName;
		this.sale_off = sale_off;
		this.banner_content = banner_content;
	}

	@Id
	@GeneratedValue
	@Column(name = "Banner_id", unique = true, nullable = false)
	public int getBannerId() {
		return this.bannerId;
	}
	public void setBannerId(int bannerId) {
		this.bannerId = bannerId;
	}
	@Column(name = "Banner_img_url", length = 150)
	public String getBannerImgUrl() {
		return this.bannerImgUrl;
	}

	public void setBannerImgUrl(String bannerImgUrl) {
		this.bannerImgUrl = bannerImgUrl;
	}

	@Column(name = "Banner_name", length = 50)
	public String getBannerName() {
		return this.bannerName;
	}

	public void setBannerName(String bannerName) {
		this.bannerName = bannerName;
	}

	@Column(name = "Banner_content")
	public String getbanner_content() {
		return this.banner_content;
	}
	
	public void setBanner_content(String banner_content) {
		this.banner_content = banner_content;
	}

	/**
	 * @return the sale_off
	 */
	@Column(name = "Sale_off")
	public String getSale_off() {
		return sale_off;
	}

	/**
	 * @param sale_off the sale_off to set
	 */
	public void setSale_off(String sale_off) {
		this.sale_off = sale_off;
	}


}
