package com.Entities;

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CartDetails generated by hbm2java
 */
@Entity
@Table(name = "Cart_Details", catalog = "Markito")
public class CartDetails{

	private int cartDetailsId;
	private Carts carts;
	private Products products;
	private Integer quantity;
	private BigDecimal price;

	public CartDetails() {
	}

	public CartDetails(int cartDetailsId, Products products) {
		this.cartDetailsId = cartDetailsId;
		this.products = products;
	}

	public CartDetails(int cartDetailsId, Carts carts, Products products, Integer quantity, BigDecimal price) {
		this.cartDetailsId = cartDetailsId;
		this.carts = carts;
		this.products = products;
		this.quantity = quantity;
		this.price = price;
	}

	@Id
	@GeneratedValue
	@Column(name = "Cart_details_id", unique = true, nullable = false)
	public int getCartDetailsId() {
		return this.cartDetailsId;
	}

	public void setCartDetailsId(int cartDetailsId) {
		this.cartDetailsId = cartDetailsId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "Cart_id")
	public Carts getCarts() {
		return this.carts;
	}

	public void setCarts(Carts carts) {
		this.carts = carts;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "Product_id", nullable = false)
	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	@Column(name = "Quantity")
	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	@Column(name = "Price", scale = 4)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

}
