package com.Entities;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Catalogs generated by hbm2java
 */
@Entity
@Table(name = "Catalogs", catalog = "Markito")
public class Catalogs{

	private String catalogId;
	private String catalogName;
	private Boolean catalogStatus;
	private Set<Categories> categorieses = new HashSet<Categories>(0);

	public Catalogs() {
	}

	public Catalogs(String catalogId, String catalogName) {
		this.catalogId = catalogId;
		this.catalogName = catalogName;
	}

	public Catalogs(String catalogId, String catalogName, Boolean catalogStatus, Set<Categories> categorieses) {
		this.catalogId = catalogId;
		this.catalogName = catalogName;
		this.catalogStatus = catalogStatus;
		this.categorieses = categorieses;
	}

	@Id

	@Column(name = "Catalog_id", unique = true, nullable = false, length = 10)
	public String getCatalogId() {
		return this.catalogId;
	}

	public void setCatalogId(String catalogId) {
		this.catalogId = catalogId;
	}

	@Column(name = "Catalog_name", nullable = false)
	public String getCatalogName() {
		return this.catalogName;
	}

	public void setCatalogName(String catalogName) {
		this.catalogName = catalogName;
	}

	@Column(name = "Catalog_status")
	public Boolean getCatalogStatus() {
		return this.catalogStatus;
	}

	public void setCatalogStatus(Boolean catalogStatus) {
		this.catalogStatus = catalogStatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "catalogs")
	public Set<Categories> getCategorieses() {
		return this.categorieses;
	}

	public void setCategorieses(Set<Categories> categorieses) {
		this.categorieses = categorieses;
	}

}
