package com.Entities;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PaymentMethod generated by hbm2java
 */
@Entity
@Table(name = "Payment_method", catalog = "Markito")
public class PaymentMethod{

	private int paymentId;
	private String paymentName;
	private String paymentSupplier;
	private String paymentDescription;
	private Set<Carts> cartses = new HashSet<Carts>(0);

	public PaymentMethod() {
	}

	public PaymentMethod(int paymentId, String paymentName, String paymentSupplier) {
		this.paymentId = paymentId;
		this.paymentName = paymentName;
		this.paymentSupplier = paymentSupplier;
	}

	public PaymentMethod(int paymentId, String paymentName, String paymentSupplier, String paymentDescription,
			Set<Carts> cartses) {
		this.paymentId = paymentId;
		this.paymentName = paymentName;
		this.paymentSupplier = paymentSupplier;
		this.paymentDescription = paymentDescription;
		this.cartses = cartses;
	}

	@Id

	@Column(name = "Payment_id", unique = true, nullable = false)
	public int getPaymentId() {
		return this.paymentId;
	}

	public void setPaymentId(int paymentId) {
		this.paymentId = paymentId;
	}

	@Column(name = "Payment_name", nullable = false)
	public String getPaymentName() {
		return this.paymentName;
	}

	public void setPaymentName(String paymentName) {
		this.paymentName = paymentName;
	}

	@Column(name = "Payment_supplier", nullable = false)
	public String getPaymentSupplier() {
		return this.paymentSupplier;
	}

	public void setPaymentSupplier(String paymentSupplier) {
		this.paymentSupplier = paymentSupplier;
	}

	@Column(name = "Payment_description")
	public String getPaymentDescription() {
		return this.paymentDescription;
	}

	public void setPaymentDescription(String paymentDescription) {
		this.paymentDescription = paymentDescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "paymentMethod")
	public Set<Carts> getCartses() {
		return this.cartses;
	}

	public void setCartses(Set<Carts> cartses) {
		this.cartses = cartses;
	}

}
