package com.Entities;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * SeoKeywords generated by hbm2java
 */
@Entity
@Table(name = "SEO_keywords", catalog = "Markito")
public class SeoKeywords{

	private int keywordId;
	private String keyword;

	public SeoKeywords() {
	}

	public SeoKeywords(int keywordId, String keyword) {
		this.keywordId = keywordId;
		this.keyword = keyword;
	}

	@Id
	@GeneratedValue
	@Column(name = "Keyword_id", unique = true, nullable = false)
	public int getKeywordId() {
		return this.keywordId;
	}

	public void setKeywordId(int keywordId) {
		this.keywordId = keywordId;
	}

	@Column(name = "Keyword")
	public String getKeyword() {
		return this.keyword;
	}

	public void setKeyword(String keyword) {
		this.keyword = keyword;
	}

}
