package entities;
// Generated Nov 7, 2017 9:59:36 AM by Hibernate Tools 5.2.5.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categories generated by hbm2java
 */
@Entity
@Table(name = "Categories", schema = "dbo", catalog = "SHOP")
public class Categories implements java.io.Serializable {

	private String categoryId;
	private Catalogs catalogs;
	private Serializable categoryName;
	private Set<Products> productses = new HashSet<Products>(0);

	public Categories() {
	}

	public Categories(String categoryId, Catalogs catalogs, Serializable categoryName) {
		this.categoryId = categoryId;
		this.catalogs = catalogs;
		this.categoryName = categoryName;
	}

	public Categories(String categoryId, Catalogs catalogs, Serializable categoryName, Set<Products> productses) {
		this.categoryId = categoryId;
		this.catalogs = catalogs;
		this.categoryName = categoryName;
		this.productses = productses;
	}

	@Id

	@Column(name = "Category_id", unique = true, nullable = false, length = 10)
	public String getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(String categoryId) {
		this.categoryId = categoryId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Catalog_id", nullable = false)
	public Catalogs getCatalogs() {
		return this.catalogs;
	}

	public void setCatalogs(Catalogs catalogs) {
		this.catalogs = catalogs;
	}

	@Column(name = "Category_name", nullable = false)
	public Serializable getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(Serializable categoryName) {
		this.categoryName = categoryName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categories")
	public Set<Products> getProductses() {
		return this.productses;
	}

	public void setProductses(Set<Products> productses) {
		this.productses = productses;
	}

}
