package entities;
// Generated Nov 7, 2017 9:59:36 AM by Hibernate Tools 5.2.5.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Customers generated by hbm2java
 */
@Entity
@Table(name = "Customers", schema = "dbo", catalog = "SHOP")
public class Customers implements java.io.Serializable {

	private Integer customerId;
	private Accounts accounts;
	private Serializable customerName;
	private boolean gender;
	private Date birthday;
	private String email;
	private Integer phone;
	private Serializable customerAddress;

	public Customers() {
	}

	public Customers(Accounts accounts, Serializable customerName, boolean gender, String email) {
		this.accounts = accounts;
		this.customerName = customerName;
		this.gender = gender;
		this.email = email;
	}

	public Customers(Accounts accounts, Serializable customerName, boolean gender, Date birthday, String email,
			Integer phone, Serializable customerAddress) {
		this.accounts = accounts;
		this.customerName = customerName;
		this.gender = gender;
		this.birthday = birthday;
		this.email = email;
		this.phone = phone;
		this.customerAddress = customerAddress;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Customer_id", unique = true, nullable = false)
	public Integer getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Username", nullable = false)
	public Accounts getAccounts() {
		return this.accounts;
	}

	public void setAccounts(Accounts accounts) {
		this.accounts = accounts;
	}

	@Column(name = "Customer_name", nullable = false)
	public Serializable getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(Serializable customerName) {
		this.customerName = customerName;
	}

	@Column(name = "Gender", nullable = false)
	public boolean isGender() {
		return this.gender;
	}

	public void setGender(boolean gender) {
		this.gender = gender;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Birthday", length = 23)
	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	@Column(name = "Email", nullable = false, length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "Phone")
	public Integer getPhone() {
		return this.phone;
	}

	public void setPhone(Integer phone) {
		this.phone = phone;
	}

	@Column(name = "Customer_Address")
	public Serializable getCustomerAddress() {
		return this.customerAddress;
	}

	public void setCustomerAddress(Serializable customerAddress) {
		this.customerAddress = customerAddress;
	}

}
