package entities;
// Generated Nov 7, 2017 9:59:36 AM by Hibernate Tools 5.2.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Pictures generated by hbm2java
 */
@Entity
@Table(name = "Pictures", schema = "dbo", catalog = "SHOP")
public class Pictures implements java.io.Serializable {

	private Integer pictureId;
	private Products products;
	private String pictureLink;

	public Pictures() {
	}

	public Pictures(Products products, String pictureLink) {
		this.products = products;
		this.pictureLink = pictureLink;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Picture_id", unique = true, nullable = false)
	public Integer getPictureId() {
		return this.pictureId;
	}

	public void setPictureId(Integer pictureId) {
		this.pictureId = pictureId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Product_id", nullable = false)
	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	@Column(name = "Picture_link", nullable = false, length = 200)
	public String getPictureLink() {
		return this.pictureLink;
	}

	public void setPictureLink(String pictureLink) {
		this.pictureLink = pictureLink;
	}

}
