package entities;
// Generated Nov 7, 2017 9:59:36 AM by Hibernate Tools 5.2.5.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Products generated by hbm2java
 */
@Entity
@Table(name = "Products", schema = "dbo", catalog = "SHOP")
public class Products implements java.io.Serializable {

	private String productId;
	private Categories categories;
	private Suppliers suppliers;
	private Serializable productName;
	private String pictureId;
	private int quantity;
	private Set<Pictures> pictureses = new HashSet<Pictures>(0);
	private Set<CartDetails> cartDetailses = new HashSet<CartDetails>(0);

	public Products() {
	}

	public Products(String productId, Categories categories, Suppliers suppliers, Serializable productName,
			String pictureId, int quantity) {
		this.productId = productId;
		this.categories = categories;
		this.suppliers = suppliers;
		this.productName = productName;
		this.pictureId = pictureId;
		this.quantity = quantity;
	}

	public Products(String productId, Categories categories, Suppliers suppliers, Serializable productName,
			String pictureId, int quantity, Set<Pictures> pictureses, Set<CartDetails> cartDetailses) {
		this.productId = productId;
		this.categories = categories;
		this.suppliers = suppliers;
		this.productName = productName;
		this.pictureId = pictureId;
		this.quantity = quantity;
		this.pictureses = pictureses;
		this.cartDetailses = cartDetailses;
	}

	@Id

	@Column(name = "Product_id", unique = true, nullable = false, length = 10)
	public String getProductId() {
		return this.productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Category_id", nullable = false)
	public Categories getCategories() {
		return this.categories;
	}

	public void setCategories(Categories categories) {
		this.categories = categories;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Supplier_id", nullable = false)
	public Suppliers getSuppliers() {
		return this.suppliers;
	}

	public void setSuppliers(Suppliers suppliers) {
		this.suppliers = suppliers;
	}

	@Column(name = "Product_name", nullable = false)
	public Serializable getProductName() {
		return this.productName;
	}

	public void setProductName(Serializable productName) {
		this.productName = productName;
	}

	@Column(name = "Picture_id", nullable = false, length = 10)
	public String getPictureId() {
		return this.pictureId;
	}

	public void setPictureId(String pictureId) {
		this.pictureId = pictureId;
	}

	@Column(name = "Quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "products")
	public Set<Pictures> getPictureses() {
		return this.pictureses;
	}

	public void setPictureses(Set<Pictures> pictureses) {
		this.pictureses = pictureses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "products")
	public Set<CartDetails> getCartDetailses() {
		return this.cartDetailses;
	}

	public void setCartDetailses(Set<CartDetails> cartDetailses) {
		this.cartDetailses = cartDetailses;
	}

}
